services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_lab4_image
    container_name: flask_lab4
    ports:
      - "5000:5000"
    volumes:
      - ./db.sqlite:/app/db.sqlite
    environment:
      FLASK_ENV: development
